# Set site.output == "epub"
output: "epub"
# Set site.image-set == "images/epub"
image-set: "images/epub"
# Turn off documentation and activate epub collection
collections:
  docs:
    output: false
  epub:
    output: true
exclude:
  # the usual excludes from _config.yml
  - run-linux.sh
  - run-mac.command
  - run-windows.bat
  - Gemfile
  - Gemfile.lock
  - README*
  - LICENSE*
  - CHANGELOG*
  - node_modules
  - eslint.json
  - gulpfile.js
  - package.json
  - package-lock.json
  - CNAME
  # exclude files we don't need for epub
  - /assets/styles
  - /*/styles/print-pdf.scss
  - /*/styles/screen-pdf.scss
  - /*/styles/web.scss
  - /*/styles/app.scss
  - /*/styles/*.dic
  - /*/index.md
  - /*/images/print-pdf
  - /*/images/screen-pdf
  - /*/images/web
  - /*/images/app
# We deliberately empty the keep_files list here,
# so that files we don't want don't end up in the epub
# but not in the manifest.
keep_files: []
# Map file extensions to media types for the opf
media-types:
  html: "application/xhtml+xml"
  xhtml: "application/xhtml+xml"
  css: "text/css"
  jpg: "image/jpeg"
  jpeg: "image/jpeg"
  gif: "image/gif"
  png: "image/png"
  svg: "image/svg+xml"
  ttf: "application/font-sfnt"
  otf: "application/font-sfnt"
  woff: "application/font-woff"
  woff2: "font/woff2"
  mp3: "audio/mpeg"
  mp4: "audio/mp4"
  ncx: "application/x-dtbncx+xml"
  txt: "text/plain"
  js: "application/x-javascript"
  unknown: "application/octet-stream"

# Since some books in this project might not use MathJax,
# we disable it by default in epub output, and
# activate it manually on output from the output script,
# which will override this setting.
# (If we don't disable MathJax here, and it is enabled
# in _config.yml, Jekyll will list the MathJax files
# in the OPF manifest of all epubs, even if they don't need
# MathJax, but the output script will not actually copy
# the MathJax files into the epub package.)
mathjax-enabled: false
